## Hash Analytics Internship 
#### Assignment 1 Introduction to Numpy.
#### Course content from udemy Learn NumPy Fundamentals (Python Library for Data Science)
#### Instructor:Derrick Sherrill

## Numpy
Numpy is a python library that is used for scientific computing, it is also very useful in data science and machine learning,the library provides users with an array data structure which has more beneficial compared to the Python list data structure."Numpy"is generated from the word “Numerical Python”.


## Installation
#### 1. Step One

First to use numpy you need to have python installed on your PC. For Linux distribution such as ubuntu that i use python comes pre-installed,and also on Mac, but for window python installer can be downloaded from [here](https://www.python.org/downloads).
#### 2. Step Two 

You can install numpy in two way using python's package manager or using anaconda.
[Anaconda](https://www.anaconda.com/distribution/) is also a package manager, the beauty of it is that installs every other dependecies you. it has distribution available for windows,linux and mac


To use pip

To use anaconda 

### Using Numpy 
Every time you want to use numpy you have to import it using the code below. You can either run your code from your terminal or use a notebook. I prefer to use jupyter notebook

In [1]:
import numpy as np

### Numpy Arrays
* Numpy arrays are faster than a python list because unlike a list it is homogenous (i.e has only one datatype).
* Numpy Arrays allows users to perform calculations across entire arrays.
* Numpy Arrays has faster access in reading and writing items
* Numpy Arrays are very efficient

### Optional Practice Array creation
The cell below creates an array of 3X4 dimesion 

In [2]:
row1 = [2,3,6,7]
row2 = [2,3,4,5]
row3 = [5,6,8,0]
make_array = np.array([row1,row2,row3])
make_array

array([[2, 3, 6, 7],
       [2, 3, 4, 5],
       [5, 6, 8, 0]])

### Reshaping Arrays


Numpy array shape indicates the shape of the array.


In [3]:
make_array.shape

(3, 4)

The array has a 3 rows and four columns

In [4]:
make_array.size

12

**size** return the number of rows multiplied by the number of columns
The size attributes is important for reshaping the array, in a case where by the you want to reshape the size of the array must not change.
**reshape()** is a function to change the shape of the array.The function takes in two arguments, the first is the number of rows and the second is the number of columns.
**reshape(rows,columns)**

In [5]:
make_array.reshape(2,6) #two rows six columns

array([[2, 3, 6, 7, 2, 3],
       [4, 5, 5, 6, 8, 0]])

In [6]:
make_array.reshape(4,3) #four rows three columns
#This also returns the transpose of the array this can be achieve by using Transpose 

array([[2, 3, 6],
       [7, 2, 3],
       [4, 5, 5],
       [6, 8, 0]])

In [7]:
make_array.T #Transpose

array([[2, 2, 5],
       [3, 3, 6],
       [6, 4, 8],
       [7, 5, 0]])

### Numpy indexing
The indexing begins from zero, so if there are 3 rows the index will be 0,1,2

1.Accessing Rows 

In [8]:
make_array[0] #first row

array([2, 3, 6, 7])

In [9]:
make_array[1] #Second Row

array([2, 3, 4, 5])

2.Accessing Columns

In [10]:
make_array[:,0] #First Column

array([2, 2, 5])

In [11]:
make_array[:,1]# second column

array([3, 3, 6])

In [12]:
#To access values by their position the row and th column should be specified.
make_array[0,3] # Accesses the first row and the fourth column

7

Numpy Array also support negative indexing
The negative index count backwards

In [13]:
make_array[0,-1] #First row last Column

7

In [14]:
make_array[-1,-1]#Last Row last Column

0

### Default Arrays
**dtype** : Argument
The dtype is used to specify the data type in the array. Since a numpy array is homogenous then the dtype specified is the data type of all the eleemnts in the array. There are various data type in numpy.
1. int16
2. int32
3. int64
4. unint16
5. unint32 
6. unint64
7. float

In [15]:
#create a new array 
new_array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype='float')
#The array was initialized with integers but they ars now float since the dtype is float
new_array

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

**np.zeros()** This function is used to initialize an array with zero as all ts elements.it is initialized with the shape of the desired array and the data type.

In [16]:
zero_array = np.zeros((3,3),dtype='float')
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

So also for ones **np.ones()** is just like **np.zeros()** but with one has all its elements

In [17]:
ones_array = np.ones((3,3), dtype='int')
ones_array

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

For an array where all the elements is a number it can be created with the function **np.full()**

In [18]:
full_array = np.full((3,3),8.0)
full_array

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

For an array for random number **np.random()**

In [19]:
random = np.random.random((3,3))
random

array([[0.26436972, 0.89887102, 0.44868079],
       [0.5438929 , 0.84833341, 0.02488342],
       [0.6811547 , 0.52789529, 0.57676459]])

### Advance indexing 
Another way to create an array with numpy is with the **np.arange()**, this function takes in 3 arguments which are the start_value, end_value and the step size.But this creates a one dimensional array so you will need to reshape the array.

In [20]:
#Create A new array 
big_array = np.arange(0,100,5)
big_array = big_array.reshape(4,5) 
big_array

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

#### Slicing 
To slice out you need start_index,end_index and the step size
array[:,start:end:step]

In [21]:
big_array[:,2:4] #Slices out the third column to the sixth column

array([[10, 15],
       [35, 40],
       [60, 65],
       [85, 90]])

#### Negative and boolean indexing
Boolean indexing is done when a condition is passed in to array. It returns the elements that where condition is true  

In [22]:
bool_array = big_array[big_array>50] #returns elements in big_array that are greater than 50 
bool_array

array([55, 60, 65, 70, 75, 80, 85, 90, 95])

Negtive indexing is done by using the a negative value to access values in the array.To access the last column or row  -1 is used 

In [23]:
neg_array = big_array[:,-2] # returns the column before the last column
neg_array

array([15, 40, 65, 90])

**np.where()** searches for the condition in function on the array

In [24]:
where_array= np.where(big_array>50,big_array,12)
where_array

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

### Array mathematics

1. **sum()** returns the sum of all the elements in the array,when axis is specified it indicates how the suming should go.When axis =0 it sums along the column, when axis =1 it sums along the row

2. **prod()** returns the product of all the elements in the array.
3. Just like in mathematics the following operations done on matrices such as  addition,subtraction,multiplication,subtraction and vector product can be done on array with numpy.
4. **ptp()** return the range of the array,when axis is specified it returns the range across columns or rows
5. **min()**,**max()**,**mean()**,**power()** performs the same operation just like in mathematics

In [25]:
big_array.sum()

950

In [26]:
big_array.sum(axis=0)

array([150, 170, 190, 210, 230])

In [27]:
big_array.sum(axis = 1)

array([ 50, 175, 300, 425])

In [28]:
test= np.arange(1,7,1)
test.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
test.prod()

720

In [30]:
y = np.array([[2,7,4],[6,8,9],[8,2,1]])
x = np.array([[3,4,8],[7,9,3],[8,3,2]])

In [31]:
x+y #Addition

array([[ 5, 11, 12],
       [13, 17, 12],
       [16,  5,  3]])

In [32]:
x-y #Subtraction

array([[ 1, -3,  4],
       [ 1,  1, -6],
       [ 0,  1,  1]])

In [33]:
x*y #multiplictaion

array([[ 6, 28, 32],
       [42, 72, 27],
       [64,  6,  2]])

In [34]:
x/y #Division

array([[1.5       , 0.57142857, 2.        ],
       [1.16666667, 1.125     , 0.33333333],
       [1.        , 1.5       , 2.        ]])

In [35]:
big_array.ptp() # 95-0 95 is the largest value and 0 is the smallest value in the big_array 

95

In [36]:
big_array.ptp(axis=1) #row

array([20, 20, 20, 20])

In [37]:
big_array.ptp(axis=0) #column

array([75, 75, 75, 75, 75])

In [38]:
big_array.min()

0

In [39]:
big_array.max()

95

In [40]:
big_array.mean()

47.5

In [41]:
z= np.power(x,y)
z

array([[       9,    16384,     4096],
       [  117649, 43046721,    19683],
       [16777216,        9,        2]])

### Broadcasting
This allows opeartions to be performed on arrays of different sizes. In broadcasting either the rows or the columns of the arrays must be compartible(i.e Both or all array must either have the same number of Columns or the same number of rows)

In [42]:
m= x+np.array([1,2,3])
m

array([[ 4,  6, 11],
       [ 8, 11,  6],
       [ 9,  5,  5]])

In [43]:
n = x+np.array([[1],[2],[3]])
n

array([[ 4,  5,  9],
       [ 9, 11,  5],
       [11,  6,  5]])

# Pandas 

Pandas is a python library used for data analysis.It uses series and pandas.Installing pandas the same method with numpy but "numpy" changes to "pandas".There are two primary component of the pandas which are Series and Dataframe.Pandas can data from csv,excel files.
### Series
A series a one-dimensional array in pandas, it can be created from integers,strings or dictionary

In [44]:
import pandas as pd

In [45]:
s = pd.Series([1,2,3,4,5,6])
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

### DataFrame
A Dataframe is a two-dimensional data structure in pandas which consists of rows and columns.It can be created from 1 or more dictionaries or Series,2D-numpy Ndarray(N-dimensional numpy array)

In [46]:
data = pd.DataFrame({"Name":["Ben","John","Sam"],
                 "Country":["Germany","Nigeria","Uganda"],
                  "Age":[22,44,78]
                 })
data

Name  Country  Age
0   Ben  Germany   22
1  John  Nigeria   44
2   Sam   Uganda   78

You can check the data types of each columns

In [47]:
data.dtypes

Name       object
Country    object
Age         int64
dtype: object

Show all the columns in a dataframe 

In [48]:
data.columns

Index(['Name', 'Country', 'Age'], dtype='object')

In [49]:
data.index # Returns the index range

RangeIndex(start=0, stop=3, step=1)

Get columns in the dataframe


In [50]:
data['Country']

0    Germany
1    Nigeria
2     Uganda
Name: Country, dtype: object

In [51]:
data['Name']

0     Ben
1    John
2     Sam
Name: Name, dtype: object

The columns can also be assessed with this method too 

In [52]:
data.Name

0     Ben
1    John
2     Sam
Name: Name, dtype: object

In [53]:
data.Country

0    Germany
1    Nigeria
2     Uganda
Name: Country, dtype: object

iloc and loc can be use to the filter the dataframe.

In [54]:
data.iloc[:1]

Name  Country  Age
0  Ben  Germany   22

In [55]:
data.loc[:1]

Name  Country  Age
0   Ben  Germany   22
1  John  Nigeria   44